Add Swerve Subsystem and Config Files
FRC-1294/frc2024 pull request #65
Opened 2023-07-29 22:37 UTC by AadityaAgni

Created SwerveSubsystem.java, which is the subsystem for the swerve drive base. While we heavily borrowed from last year's code and other team's ideas, here are the main differences:

1. SwerveSubsytem uses SwerveConfig.java, which contains the initialization for SwerveSubsystem, the ID's, and kinematics
2. Modules are now contained in SwerveConfig, but in Swerve Subsystem it is a list of modules

2023-07-29 22:45 UTC, tcdoan commented
Going forward let us add @FRC-1294/software as reviewer for every Pull Requests

2023-07-29 22:46 UTC, ConfettiRaindrop approved these changes

2023-07-29 23:17 UTC, tcdoan commented
@AadityaAgni @bredisrising Delete Constants.java

2023-07-29 23:29 UTC, tcdoan requested changes

2023-07-29 23:29 UTC, tcdoan commented on src/main/java/frc/robot/constants/SwerveConstants.java
> +  public static double backLeftRotEncoderOffset = 0;
@AadityaAgni  prefix "k" to all constants

2023-07-29 23:29 UTC, tcdoan commented on src/main/java/frc/robot/subsystems/SwerveModule.java
> +    public SwerveModule(int rotID, int transID, int rotEncoderID, double rotEncoderOffset,
Too many parameters. Abstract them into SwerveModuleConfig object that can be loaded from a json file

2023-07-29 23:54 UTC, tcdoan approved these changes
Please address the SwerveModule constructor having many parameters in the next PR

2023-08-03 00:08 UTC, Powerlax approved these changes
LGMT!

2023-08-03 00:09 UTC, merged